=== danlawand/labbd/xml/aula_xml_exemplos/artigo.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="artigo">
  <xs:complexType>
	<xs:sequence>
		<xs:element name="título" type="xs:string" minOccurs="1" maxOccurs="1"/>
		<xs:element name="autor" type="tAutor" minOccurs="1" maxOccurs="unbounded"/>
		<xs:element name="resumo" type="xs:string" minOccurs="1" maxOccurs="1"/>
		<xs:element ref="seção" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="data" type="xs:date" use="optional"/> 
  </xs:complexType>
</xs:element>

<xs:element name="seção" type="tSeção"/>

<xs:complexType name="tAutor">
	<xs:sequence>
		<xs:element name="nomea" type="xs:string" minOccurs="1" maxOccurs="1"/>
		<xs:element name="instituição" type="tInst" minOccurs="1" maxOccurs="unbounded"/>
		<xs:element name="email" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="tSeção">
	<xs:sequence>
		<xs:element name="nomes" type="xs:string" minOccurs="1" maxOccurs="1"/>
		<xs:element name="texto" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>


<xs:complexType name="tInst">
	<xs:sequence>
		<xs:element name="nomei" type="xs:string" minOccurs="1" maxOccurs="1"/>
		<xs:element name="endereço" type="xs:string" minOccurs="0" maxOccurs="1"/>
	</xs:sequence>
</xs:complexType>

</xs:schema>

=== danlawand/labbd/xml/aula_xml_exemplos/artigo.xml
<?xml version="1.0"?>
<artigo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="artigo.xsd">
	<autor>
		<nomea> Ronaldo Mello </nomea>
		<instituição> 
			<nomei> UFRGS </nomei>
			<endereço> Bento Gonçalves, 9500 </endereço>
		</instituição>
		<instituição> 
			<nomei> UFSC </nomei>
		</instituição>
		<email> ronaldo@inf.ufrgs.br </email>
	</autor>
	<autor>
		<nomea> Carlos A. Heuser </nomea>
		<instituição> 
			<nomei> UFRGS </nomei>
			<endereço> Bento Gonçalves, 9500 </endereço>
		</instituição>
		<email> heuser@inf.ufrgs.br </email>
	</autor>
	<resumo> ... </resumo>
	<seção> 
		<nomes> Introdução </nomes>
		<texto> ... </texto> 
	</seção>
</artigo>
